# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRMPipeline-conn'
    subscriptionId: '1c1103d6-8686-45fa-94cc-54b00e6390f2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'PipelineDeploymentTest'
    location: 'West US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/DaveWKrupa/AzureRMPipeline2-repo/master/DeployApplicationGateway/ApplicationGateway.json'
    deploymentMode: 'Incremental'
    deploymentName: 'AppGatewayDeployment'
    overrideParameters: '-virtualNetworkName myvnet1 -backendIPAddresses [{"IpAddress": "10.0.0.4"},{"IpAddress": "10.0.0.5"}] -vnetAddressPrefix 10.0.0.0/16 -subnetName appGWSubnet1 -subnetPrefix 10.0.0.0/24 -applicationGatewayName myAppGW1 -applicationGatewaySize Standard_Small -applicationGatewayInstanceCount 1 -frontendPort 80 -backendPort 80 -cookieBasedAffinity Disabled'
      
